# Generated by Django 3.2.25 on 2026-06-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260606_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='api.fournisseur'),
        ),
        migrations.AddField(
            model_name='depense',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('annule', 'Annulé')], default='actif', max_length=10),
        ),
        migrations.AddField(
            model_name='recette',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes', to='api.client'),
        ),
        migrations.AddField(
            model_name='recette',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('annule', 'Annulé')], default='actif', max_length=10),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recette',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
