# Generated by Django 3.2.25 on 2026-06-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20260607_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_code_expiry',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_secret',
        ),
    ]
